import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/navbar/Navbar";
import { Roboto } from 'next/font/google'
import { Toaster } from "react-hot-toast";



const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Power GYM",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={` antialiased ${roboto.className}`}
      >
        <Navbar />
        {children}
        <Toaster
          toastOptions={{
            // Define default options
            style: {
              background: '#3C8AB5',
              color: '#fff',
              fontSize: '14px'
            },
            // Default options for specific types
            success: {
              iconTheme: {
                primary: '#F7C05C',
                secondary: 'white',
              },
            },
          }}
        />
      </body>
    </html>
  );
}
